import Head from 'next/head'
import { QuizCard } from './components/quiz-card'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Quiz app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white bg-black">
      <QuizCard/>
      </main>
      
    </div>
  )
}
